# Application Port configuration
server.port=8080

spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/lead_db}

# Logging Configurations
logging.level.com.sales.leadqualifier=DEBUG
logging.level.org.springframework.web=INFO

gemini.api.key=${GEMINI_API_KEY}